# wpa_supplicant configuration for SpacemiT K3 Pico-ITX
ctrl_interface=/data/vendor/wifi/wpa/sockets
update_config=1
device_name=K3_Pico_ITX
manufacturer=SpacemiT
model_name=K3 Pico-ITX
model_number=K3
serial_number=0
device_type=10-0050F204-5
config_methods=physical_display virtual_push_button
p2p_disabled=1
external_sim=0
